name: CI Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --force

  custom-script:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run custom script
      run: |
        echo "Running custom script..."
        npm install
        npm install eslint-config-react-app
        npm install --save-dev @babel/plugin-proposal-private-property-in-object
        npm run build 
        npm run test
        
    - name: codeql
      uses: actions/jeanegpedrosa/github-actions-dotnet-webapp/.github/workflows/codeql.yml@main
